workflows:
  my-workflow:
    scripts: 
      - name: multi-line script
        script: |
          xcode-project run-tests \
            --workspace TicTacToe.xcworkspace \
            --scheme TicTacToe
  