workflows:
  my-workflow:
    scripts: 
      - name: multi-line script
        script: |
        xcode-project run-tests \
          --workspace MyAwesomeApp.xcworkspace \
          --scheme MyAwesomeApp \
          --device "iPhone 11"